import React from 'react';
import {
  Activity, Airplay, AlertCircle, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight,
  Anchor, Aperture, Archive, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AtSign, Award,
  Banknote, BarChart, BarChart2, Battery, BatteryCharging, Beer, Bell, Bike, Bitcoin, Bluetooth, Bold,
  Book, BookOpen, Bookmark, Box, Briefcase, Bug, Building,
  Calculator, Calendar, CalendarCheck, Camera, Car, Cast, Cat, Check, CheckCircle, CheckSquare,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Chrome, Circle, Clipboard, Clock, Cloud,
  CloudLightning, CloudRain, CloudSnow, Code, Coffee, Command, Compass, Copy, Cpu, CreditCard, Crop, Crown,
  Database, Diamond, Disc, Dog, DollarSign, DownloadCloud, Droplet,
  Edit, Eye, EyeOff,
  Facebook, Factory, FastForward, Feather, File, FileAudio, FileImage, FileText, FileVideo, Film, Filter, Flag, Flame, FlaskConical, Folder, Frown,
  Gamepad, Ghost, Gift, GitBranch, GitCommit, Github, GitMerge, GitPullRequest, Globe, Grid,
  Hammer, Hand, HardDrive, Hash, Headphones, Heart, HelpCircle, Hexagon, Home, Image as ImageIcon, Inbox, Info, Instagram, Italic,
  Key,
  Laptop, Layers, Layout, Leaf, LifeBuoy, Lightbulb, Link, Link2, Linkedin, List, Loader, Lock, LogOut,
  Mail, Map, MapPin, Maximize, Megaphone, Menu, MessageCircle, MessageSquare, Mic, Minimize, Monitor, Moon, MoreHorizontal, MoreVertical, Mouse, Move, Music,
  Navigation,
  Octagon,
  Package, Palette, Paperclip, Pause, PauseCircle, PenTool, Pencil, Percent, Phone, PieChart, Pin, Pizza, Plane, Play, PlayCircle, Plus, PlusCircle, Pocket, Power, Printer,
  Radio, RefreshCw, Repeat, Rewind, Rocket,
  Save, Scissors, Search, Send, Server, Settings, Share, Share2, Shield, Ship, Shirt, ShoppingBag, ShoppingCart, Shuffle, Sidebar, Siren, Skull, Slack, Slash, Sliders, Smartphone, Smile as SmileIcon, Snowflake, Sparkles, Speaker, Square, Star, Stethoscope, StopCircle, Sun, Sword,
  Tablet, Tag, Target, Tent, Terminal, Thermometer, ThumbsDown, ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight, Train, Trash, Trash2, TrendingDown, TrendingUp, Triangle, Trophy, Truck, Tv, Twitch, Twitter,
  Umbrella, Underline, Unlock, Upload, User, UserCheck, UserMinus, UserPlus, Users, Utensils,
  Video, VideoOff, Voicemail, Volume, Volume1, Volume2, VolumeX,
  Wallet, Wand, Watch, Wifi, WifiOff, Wind, Wine, Wrench,
  X, XCircle,
  Youtube,
  Zap, ZapOff, ZoomIn, ZoomOut
} from 'lucide-react';

export const iconMap: Record<string, React.ComponentType<{ size?: number; strokeWidth?: number; style?: React.CSSProperties }>> = {
  Activity, Airplay, AlertCircle, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight,
  Anchor, Aperture, Archive, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AtSign, Award,
  Banknote, BarChart, BarChart2, Battery, BatteryCharging, Beer, Bell, Bike, Bitcoin, Bluetooth, Bold,
  Book, BookOpen, Bookmark, Box, Briefcase, Bug, Building,
  Calculator, Calendar, CalendarCheck, Camera, Car, Cast, Cat, Check, CheckCircle, CheckSquare,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Chrome, Circle, Clipboard, Clock, Cloud,
  CloudLightning, CloudRain, CloudSnow, Code, Coffee, Command, Compass, Copy, Cpu, CreditCard, Crop, Crown,
  Database, Diamond, Disc, Dog, DollarSign, DownloadCloud, Droplet,
  Edit, Eye, EyeOff,
  Facebook, Factory, FastForward, Feather, File, FileAudio, FileImage, FileText, FileVideo, Film, Filter, Flag, Flame, FlaskConical, Folder, Frown,
  Gamepad, Ghost, Gift, GitBranch, GitCommit, Github, GitMerge, GitPullRequest, Globe, Grid,
  Hammer, Hand, HardDrive, Hash, Headphones, Heart, HelpCircle, Hexagon, Home, ImageIcon, Inbox, Info, Instagram, Italic,
  Key,
  Laptop, Layers, Layout, Leaf, LifeBuoy, Lightbulb, Link, Link2, Linkedin, List, Loader, Lock, LogOut,
  Mail, Map, MapPin, Maximize, Megaphone, Menu, MessageCircle, MessageSquare, Mic, Minimize, Monitor, Moon, MoreHorizontal, MoreVertical, Mouse, Move, Music,
  Navigation,
  Octagon,
  Package, Palette, Paperclip, Pause, PauseCircle, PenTool, Pencil, Percent, Phone, PieChart, Pin, Pizza, Plane, Play, PlayCircle, Plus, PlusCircle, Pocket, Power, Printer,
  Radio, RefreshCw, Repeat, Rewind, Rocket,
  Save, Scissors, Search, Send, Server, Settings, Share, Share2, Shield, Ship, Shirt, ShoppingBag, ShoppingCart, Shuffle, Sidebar, Siren, Skull, Slack, Slash, Sliders, Smartphone, SmileIcon, Snowflake, Sparkles, Speaker, Square, Star, Stethoscope, StopCircle, Sun, Sword,
  Tablet, Tag, Target, Tent, Terminal, Thermometer, ThumbsDown, ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight, Train, Trash, Trash2, TrendingDown, TrendingUp, Triangle, Trophy, Truck, Tv, Twitch, Twitter,
  Umbrella, Underline, Unlock, Upload, User, UserCheck, UserMinus, UserPlus, Users, Utensils,
  Video, VideoOff, Voicemail, Volume, Volume1, Volume2, VolumeX,
  Wallet, Wand, Watch, Wifi, WifiOff, Wind, Wine, Wrench,
  X, XCircle,
  Youtube,
  Zap, ZapOff, ZoomIn, ZoomOut
};

export const iconKeys = Object.keys(iconMap);
